### ISSUE TITLE
Unhandled exception on query string whern used with deepFreeze.

### ISSUE THREAD

**Issue by Recmo** [zapier/redux-router-kit#1]
As part of our development testing, we use [deepFreeze](https://www.npmjs.com/package/deep-freeze) on our state like so:

```js
  const deepFreeze = require('deep-freeze');
  const reducerWrap = next => (...args) => deepFreeze(next(state));
  const store = createStore(reducerWrap(combineReducers({router})), enhancers(appRoutes));
```

This fails when a query parameter is passed because `router.next.query` does not have the `Object` prototype and deep-freeze expects it for `hasOwnProperty`.

You can argue deep-freeze is at fault for expecting this property (it should rather use `Object.getOwnPropertyNames`).

**Comment by Recmo** [comment]
Here's the respective issue in deep-freeze: https://github.com/substack/deep-freeze/issues/13

**Comment by bryanhelmig** [comment]
Definitely seems like a `deep-freeze` oddity. I might suggest replacing it with your own inlined version? That is actually what we've done at `zapier`!
